# The operator registry smart contract address
operators_registry = "0x..."

# Postgres database configuration
db_url = "postgres://boltadmin:$PASSWORD@remotebeast:5412/bolt_registry"

# Beacon node connection
beacon_url = "http://remotebeast:44400"

# Lido keys API
keys_api_url = "http://34.88.187.80:30303/v1/preconfs/lido-bolt/validators"
