[profile.default]
evm_version = "cancun"
solc = "0.8.27"
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]

# silence some warnings during compilation
# https://book.getfoundry.sh/reference/config/solidity-compiler#ignored_error_codes
ignored_error_codes = [3628, 1878, 5574]
ignored_warnings_from = ["lib/openzeppelin-contracts/contracts"]

remappings = [
    # Bolt-Registry remappings
    "@openzeppelin-v4.9.0/=lib/openzeppelin-contracts-v4.9.0/",
    "@openzeppelin-v5.0.0/=lib/openzeppelin-contracts-v5.0.0/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/foundry-upgrades/=lib/openzeppelin-foundry-upgrades/",
    "@symbiotic/middleware-sdk/=lib/middleware-sdk/src/",
    "@symbiotic/core/=lib/core/src/",
    "@eigenlayer/=lib/eigenlayer-contracts/",

    # Access the EigenLayer dependencies. Needed for tests.
    "@openzeppelin/contracts-eigenlayer/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-v4.9.0/contracts/",

    # OpenZeppelin remappings contexts
    "lib/openzeppelin-contracts/:@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "lib/openzeppelin-contracts-upgradeable/:@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",

    # Symbiotic remappings contexts
    "lib/middleware-sdk/:@symbiotic/=lib/core/src/",

    # EigenLayer remapping contexts
    "lib/eigenlayer-contracts/:@openzeppelin-upgrades/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-upgradeable-v4.9.0/",
    # Note: we pin the openzeppelin version used for EL to 4.9.0. When/if EL upgrades to v5, we need to update this.
    # "lib/eigenlayer-contracts/:@openzeppelin/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-v4.9.0/",
    "lib/eigenlayer-contracts/:@openzeppelin/=lib/openzeppelin-contracts-v4.9.0",
    "lib/eigenlayer-contracts/:ds-test/=lib/eigenlayer-contracts/lib/ds-test/src/",
    "lib/eigenlayer-contracts/:forge-std/=lib/eigenlayer-contracts/lib/forge-std/src/"
]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
holesky = "${ETH_RPC_URL_HOLESKY}"

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

[fuzz]
runs = 4096
max_test_rejects = 262144
