name: Registry Contracts CI

on:
  push:
    paths:
      - "contracts/**"
    branches:
      - main
  pull_request:
    paths:
      - "contracts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: forge test --via-ir -vvv
        working-directory: contracts

      - name: Run forge fmt
        run: forge fmt --check
        working-directory: contracts
